"""Contexto de cada capítulo donde habla Jesús: a quién habla (si el pasaje no
lo dice) y qué estaba pasando."""

CAPITULOS = {
    # Mateo
    'mat 3': ('Juan el Bautista', 'Jesús llega de Galilea al Jordán para ser bautizado por Juan. Juan se resiste, porque sabe que él es quien necesita ser bautizado por Jesús.'),
    'mat 4': ('el diablo', 'Después de su bautismo, Jesús ayuna cuarenta días en el desierto y es tentado por el diablo. Luego comienza a predicar en Galilea y llama a sus primeros discípulos junto al mar.'),
    'mat 5': ('sus discípulos y la multitud', 'En un monte de Galilea, Jesús comienza el Sermón del Monte: las bienaventuranzas y una justicia que va más allá de la letra de la Ley, hasta el corazón.'),
    'mat 6': ('sus discípulos y la multitud', 'El Sermón del Monte continúa: Jesús enseña a dar, orar y ayunar en secreto, a hacer tesoros en el cielo y a no vivir con afán por el mañana.'),
    'mat 7': ('sus discípulos y la multitud', 'Jesús termina el Sermón del Monte: no juzgar, pedir al Padre con confianza, entrar por la puerta estrecha y edificar la vida sobre la roca de sus palabras.'),
    'mat 8': ('la multitud', 'Al bajar del monte, Jesús sana a un leproso, al siervo de un centurión y a muchos enfermos; calma una tempestad y libera a dos endemoniados.'),
    'mat 9': ('la multitud', 'En Capernaum, Jesús perdona y sana a un paralítico, llama a Mateo el publicano, come con pecadores y sana a muchos. Al ver a la gente como ovejas sin pastor, se compadece.'),
    'mat 10': ('los doce', 'Jesús envía a sus doce apóstoles a predicar y sanar. Les advierte de la persecución, pero les recuerda que el Padre cuida hasta de los pajarillos.'),
    'mat 11': ('la multitud', 'Juan el Bautista, desde la cárcel, pregunta si Jesús es el que había de venir. Jesús responde, reprende a las ciudades que no se arrepintieron e invita a los cansados a ir a él.'),
    'mat 12': ('los fariseos', 'Los fariseos acusan a los discípulos de quebrantar el sábado y a Jesús de echar demonios por Beelzebub. Jesús les responde que él es Señor del sábado.'),
    'mat 13': ('la multitud', 'Sentado en una barca junto al mar, Jesús enseña en parábolas el reino de los cielos: el sembrador, el trigo y la cizaña, la semilla de mostaza, el tesoro escondido.'),
    'mat 14': ('sus discípulos', 'Tras la muerte de Juan el Bautista, Jesús alimenta a cinco mil personas y, de noche, camina sobre el mar hacia la barca de sus discípulos.'),
    'mat 15': ('los fariseos', 'Jesús confronta a los fariseos por sus tradiciones humanas, sana a la hija de una mujer cananea por su fe y alimenta a cuatro mil personas.'),
    'mat 16': ('sus discípulos', 'Cerca de Cesarea de Filipo, Pedro confiesa que Jesús es el Cristo, el Hijo del Dios viviente. Jesús anuncia por primera vez su muerte y su resurrección.'),
    'mat 17': ('sus discípulos', 'Jesús se transfigura delante de Pedro, Jacobo y Juan. Al bajar del monte sana a un muchacho y habla de la fe como un grano de mostaza.'),
    'mat 18': ('sus discípulos', 'Los discípulos discuten quién es el mayor. Jesús les enseña a ser como niños, a buscar a la oveja perdida y a perdonar setenta veces siete.'),
    'mat 19': ('sus discípulos', 'Camino a Judea, Jesús responde sobre el divorcio, bendice a los niños y habla con un joven rico que no quiere dejar sus riquezas.'),
    'mat 20': ('sus discípulos', 'Jesús cuenta la parábola de los obreros de la viña, anuncia otra vez su muerte, enseña que el mayor es el que sirve y sana a dos ciegos en Jericó.'),
    'mat 21': ('la multitud y los principales sacerdotes', 'Jesús entra en Jerusalén montado en un asno, purifica el templo y, ante los líderes que cuestionan su autoridad, cuenta parábolas de juicio.'),
    'mat 22': ('los fariseos', 'En el templo, fariseos, herodianos y saduceos intentan atrapar a Jesús con preguntas. Él resume la Ley en amar a Dios y al prójimo.'),
    'mat 23': ('la multitud y sus discípulos', 'En el templo, Jesús denuncia la hipocresía de los escribas y fariseos con siete «¡ay de vosotros!» y llora por Jerusalén.'),
    'mat 24': ('sus discípulos', 'En el monte de los Olivos, los discípulos preguntan por el fin. Jesús anuncia la destrucción del templo, señales y su venida, y les pide velar.'),
    'mat 25': ('sus discípulos', 'Jesús sigue hablando de su venida: las diez vírgenes, los talentos y el juicio en que separará a las ovejas de los cabritos.'),
    'mat 26': ('sus discípulos', 'Llega la Pascua. Jesús es ungido en Betania, celebra la última cena, ora en Getsemaní y es arrestado y llevado ante el concilio.'),
    'mat 27': ('Pilato', 'Jesús es juzgado ante Pilato, condenado, burlado y crucificado. Desde la cruz clama a su Padre.'),
    'mat 28': ('sus discípulos', 'Al amanecer del primer día de la semana, Jesús resucita. Se aparece a las mujeres y a los once en Galilea, y los envía a hacer discípulos a todas las naciones.'),
    # Marcos
    'mar 1': ('sus discípulos', 'Jesús comienza a predicar en Galilea: el reino de Dios se ha acercado. Llama a sus primeros discípulos, enseña con autoridad en Capernaum y sana a muchos.'),
    'mar 2': ('los escribas', 'En Capernaum, Jesús perdona y sana a un paralítico, llama a Leví, come con pecadores y responde a quienes critican a sus discípulos por el ayuno y el sábado.'),
    'mar 3': ('los fariseos', 'Jesús sana en sábado a un hombre de mano seca, elige a los doce y responde a quienes dicen que echa demonios por Beelzebub.'),
    'mar 4': ('la multitud', 'Desde una barca, Jesús enseña en parábolas: el sembrador, la lámpara, la semilla que crece sola, el grano de mostaza. Después calma la tempestad.'),
    'mar 5': ('la multitud', 'Jesús libera a un endemoniado en Gadara, sana a una mujer que tocó su manto y resucita a la hija de Jairo.'),
    'mar 6': ('sus discípulos', 'Jesús es rechazado en Nazaret, envía a los doce, alimenta a cinco mil y camina sobre el mar.'),
    'mar 7': ('los fariseos', 'Jesús confronta las tradiciones de los fariseos, sana a la hija de una mujer sirofenicia y a un sordomudo.'),
    'mar 8': ('sus discípulos', 'Jesús alimenta a cuatro mil, sana a un ciego en Betsaida y, tras la confesión de Pedro, anuncia su muerte y llama a tomar la cruz.'),
    'mar 9': ('sus discípulos', 'Jesús se transfigura, libera a un muchacho que su padre trae con poca fe y enseña que el primero debe ser el servidor de todos.'),
    'mar 10': ('sus discípulos', 'Camino a Jerusalén, Jesús habla del matrimonio, bendice a los niños, conversa con un joven rico y sana al ciego Bartimeo.'),
    'mar 11': ('sus discípulos', 'Jesús entra en Jerusalén, maldice una higuera, purifica el templo y enseña sobre la fe y el perdón.'),
    'mar 12': ('los principales sacerdotes, los escribas y los fariseos', 'En el templo, los líderes interrogan a Jesús. Él cuenta la parábola de los labradores, responde sobre el tributo y la resurrección, y alaba la ofrenda de una viuda pobre.'),
    'mar 13': ('sus discípulos', 'En el monte de los Olivos, Jesús anuncia la destrucción del templo y su venida, y pide a sus discípulos que velen.'),
    'mar 14': ('sus discípulos', 'Jesús es ungido en Betania, celebra la última cena, ora en Getsemaní y es arrestado y juzgado ante el concilio.'),
    'mar 15': ('Pilato', 'Jesús es entregado a Pilato, condenado y crucificado. Desde la cruz clama a su Padre.'),
    'mar 16': ('los once', 'Jesús resucita, se aparece a María Magdalena y a los once, y los envía a predicar el evangelio a toda criatura.'),
    # Lucas
    'luc 2': ('María y José', 'A los doce años, Jesús sube con sus padres a Jerusalén para la Pascua. Se queda en el templo y sus padres lo buscan angustiados durante tres días.'),
    'luc 4': ('el diablo', 'Jesús es tentado en el desierto. Luego lee en la sinagoga de Nazaret la profecía de Isaías y anuncia que se cumple hoy; lo rechazan, y sigue sanando en Capernaum.'),
    'luc 5': ('Pedro', 'Junto al lago de Genesaret, Jesús da a Pedro una pesca milagrosa y lo llama. Sana a un leproso y a un paralítico, llama a Leví y come con pecadores.'),
    'luc 6': ('sus discípulos y la multitud', 'Jesús responde sobre el sábado, elige a los doce y, en un llano, enseña las bienaventuranzas, el amor a los enemigos y a no juzgar.'),
    'luc 7': ('la multitud', 'Jesús sana al siervo de un centurión, resucita al hijo de una viuda en Naín, habla de Juan el Bautista y perdona a una mujer pecadora en casa de un fariseo.'),
    'luc 8': ('sus discípulos', 'Jesús recorre ciudades con los doce y algunas mujeres. Cuenta la parábola del sembrador, calma la tempestad, libera a un endemoniado y sana a una mujer y a la hija de Jairo.'),
    'luc 9': ('sus discípulos', 'Jesús envía a los doce, alimenta a cinco mil, escucha la confesión de Pedro, se transfigura y emprende con firmeza el camino a Jerusalén.'),
    'luc 10': ('sus discípulos', 'Jesús envía a setenta discípulos, responde a un doctor de la ley con la parábola del buen samaritano y visita a Marta y María.'),
    'luc 11': ('sus discípulos', 'Jesús enseña a orar, responde a quienes lo acusan de echar demonios por Beelzebub y denuncia la hipocresía de fariseos y doctores de la ley.'),
    'luc 12': ('sus discípulos y la multitud', 'Ante una gran multitud, Jesús advierte contra la hipocresía y la avaricia, enseña a no afanarse y a estar preparados para su venida.'),
    'luc 13': ('la multitud', 'Jesús llama al arrepentimiento, sana a una mujer encorvada en sábado y habla de la puerta angosta y de su dolor por Jerusalén.'),
    'luc 14': ('los fariseos', 'En casa de un fariseo principal, Jesús sana en sábado, enseña a tomar el último lugar e invitar a los pobres, y habla del costo de seguirlo.'),
    'luc 15': ('los fariseos y los escribas', 'Los fariseos murmuran porque Jesús recibe a pecadores y come con ellos. Él responde con tres parábolas: la oveja perdida, la moneda perdida y el hijo pródigo.'),
    'luc 16': ('sus discípulos', 'Jesús cuenta la parábola del mayordomo infiel, advierte a los fariseos avaros y relata la historia del rico y Lázaro.'),
    'luc 17': ('sus discípulos', 'Jesús enseña sobre el perdón, la fe y el servicio; sana a diez leprosos, de los que solo uno vuelve a dar gracias, y habla de la venida del reino.'),
    'luc 18': ('sus discípulos', 'Jesús enseña a orar sin desmayar, cuenta la parábola del fariseo y el publicano, bendice a los niños, habla con un joven rico y sana a un ciego en Jericó.'),
    'luc 19': ('Zaqueo', 'En Jericó, Jesús entra en casa de Zaqueo. Cuenta la parábola de las minas, entra en Jerusalén, llora por la ciudad y purifica el templo.'),
    'luc 20': ('los principales sacerdotes, los escribas y los ancianos', 'En el templo, los líderes cuestionan la autoridad de Jesús. Él cuenta la parábola de los labradores y responde sobre el tributo y la resurrección.'),
    'luc 21': ('sus discípulos', 'Jesús alaba la ofrenda de una viuda pobre y anuncia la destrucción del templo, señales del fin y su venida.'),
    'luc 22': ('sus discípulos', 'Jesús celebra la última cena, anuncia la negación de Pedro, ora en el monte de los Olivos con angustia y es arrestado y juzgado.'),
    'luc 23': ('Pilato', 'Jesús es juzgado ante Pilato y Herodes y crucificado. Desde la cruz perdona, promete el paraíso a un malhechor arrepentido y entrega su espíritu al Padre.'),
    'luc 24': ('sus discípulos', 'Jesús resucita. Camina con dos discípulos hacia Emaús, se aparece a los once, les abre el entendimiento de las Escrituras y asciende al cielo.'),
    # Juan
    'jua 1': ('sus discípulos', 'Juan el Bautista señala a Jesús como el Cordero de Dios. Los primeros discípulos lo siguen, y Jesús llama a Felipe y a Natanael.'),
    'jua 2': ('su madre y los judíos', 'Jesús convierte el agua en vino en una boda en Caná y, en la Pascua, echa a los mercaderes del templo.'),
    'jua 3': ('Nicodemo', 'De noche, Nicodemo, un principal de los judíos, va a ver a Jesús. Jesús le habla de nacer de nuevo y del amor de Dios que dio a su Hijo.'),
    'jua 4': ('una mujer samaritana', 'Junto al pozo de Jacob, Jesús pide agua a una mujer samaritana y le ofrece agua viva. Después sana al hijo de un oficial del rey.'),
    'jua 5': ('los judíos', 'Jesús sana en sábado a un hombre enfermo desde hace treinta y ocho años junto al estanque de Betesda, y responde a los judíos que lo persiguen por ello.'),
    'jua 6': ('la multitud', 'Jesús alimenta a cinco mil, camina sobre el mar y en Capernaum se revela como el pan de vida. Muchos discípulos se vuelven atrás.'),
    'jua 7': ('los judíos', 'En la fiesta de los Tabernáculos, Jesús enseña en el templo entre división y amenazas, e invita al que tiene sed a ir a él y beber.'),
    'jua 8': ('los fariseos', 'Jesús perdona a una mujer sorprendida en adulterio y, en el templo, se revela como la luz del mundo ante los fariseos que discuten con él.'),
    'jua 9': ('un ciego de nacimiento', 'Jesús sana en sábado a un hombre ciego de nacimiento. Los fariseos lo expulsan, y Jesús lo busca para revelarse a él.'),
    'jua 10': ('los judíos', 'Jesús se presenta como la puerta de las ovejas y el buen pastor que da su vida por ellas. En la fiesta de la Dedicación intentan apedrearlo.'),
    'jua 11': ('Marta y sus discípulos', 'Lázaro, el amigo de Jesús, muere en Betania. Jesús consuela a Marta y María, llora y resucita a Lázaro.'),
    'jua 12': ('la multitud', 'María unge a Jesús en Betania. Jesús entra en Jerusalén y anuncia que ha llegado la hora en que el Hijo del hombre será glorificado.'),
    'jua 13': ('sus discípulos', 'En la última cena, Jesús lava los pies a sus discípulos, anuncia la traición de Judas y les da un mandamiento nuevo: que se amen unos a otros.'),
    'jua 14': ('sus discípulos', 'En la última cena, Jesús consuela a sus discípulos turbados: va a prepararles lugar, es el camino, la verdad y la vida, y les enviará el Consolador.'),
    'jua 15': ('sus discípulos', 'Jesús se presenta como la vid verdadera: sus discípulos deben permanecer en él y amarse unos a otros, aunque el mundo los aborrezca.'),
    'jua 16': ('sus discípulos', 'Jesús prepara a sus discípulos para su partida: el Espíritu vendrá, su tristeza se convertirá en gozo, y él ha vencido al mundo.'),
    'jua 17': ('el Padre', 'Antes de ir a la cruz, Jesús alza los ojos al cielo y ora al Padre por sí mismo, por sus discípulos y por todos los que creerán en él.'),
    'jua 18': ('Pilato', 'Jesús es arrestado en el huerto, interrogado por el sumo sacerdote y llevado ante Pilato, a quien le habla de su reino, que no es de este mundo.'),
    'jua 19': ('Pilato', 'Jesús es azotado, condenado y crucificado. Desde la cruz encomienda a su madre al discípulo amado y dice: «Consumado es».'),
    'jua 20': ('María Magdalena y sus discípulos', 'Jesús resucita. Se aparece a María Magdalena, a los discípulos encerrados por miedo y, ocho días después, a Tomás.'),
    'jua 21': ('Pedro', 'Junto al mar de Tiberias, Jesús resucitado da a sus discípulos una pesca milagrosa, come con ellos y restaura a Pedro, que lo había negado tres veces.'),
    # Hechos
    'hch 1': ('los apóstoles', 'Durante cuarenta días después de resucitar, Jesús se muestra a sus apóstoles. Antes de subir al cielo les promete el Espíritu Santo y los envía como testigos.'),
    'hch 9': ('Saulo', 'Saulo va a Damasco a perseguir a los cristianos cuando una luz del cielo lo rodea y Jesús le habla. Después, el Señor envía a Ananías a orar por él.'),
    'hch 10': ('Pedro', 'En Jope, Pedro tiene una visión de animales impuros y oye la voz del Señor. Así Dios lo prepara para llevar el evangelio a la casa del centurión Cornelio.'),
    'hch 11': ('Pedro', 'En Jerusalén, Pedro cuenta a los creyentes la visión y las palabras del Señor que lo llevaron a predicar a los gentiles.'),
    'hch 18': ('Pablo', 'En Corinto, Pablo enfrenta oposición. De noche, el Señor le habla en visión y le pide que no tema y siga hablando.'),
    'hch 20': ('los ancianos de Éfeso', 'Pablo se despide de los ancianos de Éfeso y les recuerda unas palabras del Señor Jesús que no están en los evangelios.'),
    'hch 22': ('Pablo', 'Arrestado en Jerusalén, Pablo cuenta a la multitud cómo Jesús le habló camino a Damasco y después en el templo.'),
    'hch 23': ('Pablo', 'Preso en Jerusalén y amenazado de muerte, Pablo recibe de noche la visita del Señor, que lo anima.'),
    'hch 26': ('Pablo', 'Ante el rey Agripa, Pablo cuenta cómo Jesús le habló camino a Damasco y lo envió a abrir los ojos de los gentiles.'),
    # Cartas
    '1co 11': ('sus discípulos', 'Pablo corrige a los corintios por cómo celebran la Cena del Señor y les recuerda lo que Jesús dijo la noche en que fue entregado.'),
    '2co 12': ('Pablo', 'Pablo cuenta que pidió tres veces al Señor que le quitara un aguijón en la carne, y la respuesta que recibió.'),
    # Apocalipsis
    'apo 1': ('Juan', 'En la isla de Patmos, en el día del Señor, Juan oye una gran voz y ve a Jesús glorificado en medio de siete candeleros.'),
    'apo 2': ('las iglesias de Asia', 'Jesús dicta a Juan cartas para las iglesias de Éfeso, Esmirna, Pérgamo y Tiatira: las elogia, las corrige y promete recompensa al que venza.'),
    'apo 3': ('las iglesias de Asia', 'Jesús dicta cartas para las iglesias de Sardis, Filadelfia y Laodicea. A los tibios les dice: «Yo estoy a la puerta y llamo».'),
    'apo 16': ('la iglesia', 'En medio de las copas de la ira de Dios derramadas sobre la tierra, Jesús interrumpe con una advertencia a velar.'),
    'apo 21': ('Juan', 'Juan ve un cielo nuevo y una tierra nueva, y la nueva Jerusalén. El que está sentado en el trono anuncia que hace nuevas todas las cosas.'),
    'apo 22': ('la iglesia', 'Al final de la revelación, Jesús promete tres veces: «He aquí, vengo presto», e invita al que tiene sed a tomar del agua de la vida.'),
}
