# ---------------------------------------------------------------- PROFETAS (reyes y profetas)
add("1sa-16-7", "profetas", "1 Samuel 16:7", "1 Samuel", "Yavé",
 "No mires a su parecer, ni a lo grande de su estatura, porque yo lo desecho; porque Yavé mira no lo que el hombre mira; pues que el hombre mira lo que está delante de sus ojos, mas Yavé mira el corazón.",
 "El profeta Samuel", ["Samuel", "David", "Isaí", "Eliab"],
 "Hacia el año 1025 a. C. El rey Saúl había sido rechazado por su desobediencia y Dios envía a Samuel a Belén para ungir a un nuevo rey entre los hijos de Isaí.",
 "Samuel vio a Eliab, el hijo mayor, alto y de buena presencia, y pensó que era el elegido. Pero Dios había escogido al menor, David, que cuidaba las ovejas.",
 "Juzgar por las apariencias y sentirse invisible o menospreciado.",
 "Dios corrige incluso al profeta: el valor de una persona no está en su aspecto, su estatura o su posición. David, el que ni siquiera fue invitado a la reunión, era el elegido. Dios mira el corazón.",
 "Si hoy estás enfrentando rechazo por tu apariencia, tu edad o tu origen, o sientes que nadie te toma en cuenta, recuerda que Dios te mira de otra manera. Y si tú estás juzgando a otros por lo externo, pide a Dios ojos como los suyos.",
 "Señor, tú miras mi corazón. Hoy renuncio a medir mi valor por la opinión de los demás o por mi apariencia. Dame un corazón conforme al tuyo y enséñame a mirar a otros como tú los miras. Amén.",
 ["fe", "tristeza"], ["autoestima", "elección de Dios", "corazón", "apariencias"], ["rechazo", "baja autoestima", "prejuicio"])

add("sal-32-8", "profetas", "Salmos 32:8", "Salmos", "Yavé",
 "Te haré entender, y te enseñaré el camino en que debes andar: sobre ti fijaré mis ojos.",
 "David (y quien ora con este salmo)", ["David"],
 "Salmo de David, rey de Israel hacia el año 1000 a. C. En medio del salmo, la voz cambia y es Dios mismo quien responde.",
 "David describe cómo, mientras calló su pecado, se le secaban los huesos; y cómo encontró alivio al confesarlo. Entonces Dios le promete guiarlo.",
 "La confusión sobre qué camino tomar y el peso de un pecado no confesado.",
 "Después de la confesión viene la dirección. Dios promete tres cosas: hacer entender, enseñar el camino y mantener sus ojos sobre nosotros. No nos deja adivinar solos.",
 "Si hoy estás enfrentando una decisión y no sabes qué camino tomar, primero pon en orden tu corazón delante de Dios. Luego pídele dirección concreta y mantente atento: Él promete enseñarte y no quitarte la mirada de encima.",
 "Señor, no sé qué camino tomar. Hoy renuncio a la ansiedad de decidir solo. Enséñame el camino en que debo andar y fija tus ojos sobre mí. Amén.",
 ["obediencia", "ansiedad"], ["dirección", "decisiones", "sabiduría", "confesión"], ["confusión", "indecisión", "ansiedad"])

add("sal-46-10", "profetas", "Salmos 46:10", "Salmos", "Dios",
 "Estad quietos, y conoced que yo soy Dios: ensalzado he de ser entre las gentes, ensalzado seré en la tierra.",
 "El pueblo de Israel en tiempos de guerra", ["hijos de Coré"],
 "Salmo de los hijos de Coré, cantado en el templo de Jerusalén. Celebra que Dios es refugio de su pueblo.",
 "El salmo describe la tierra temblando, montes cayendo al mar y naciones en guerra. En medio del caos, Dios habla.",
 "La agitación, el ruido interior y la ansiedad ante un mundo que parece derrumbarse.",
 "«Estad quietos» significa literalmente «soltad, dejad de luchar». Dios invita a detener el esfuerzo desesperado para reconocer que Él tiene el control. La quietud no es pasividad, sino confianza.",
 "Si hoy estás enfrentando ansiedad o sientes que todo se mueve a tu alrededor, detente. Apaga el ruido cinco minutos, respira despacio y repite: «Tú eres Dios, yo no». Suelta lo que no puedes controlar.",
 "Señor, mi mente no para y todo a mi alrededor tiembla. Hoy renuncio a la ansiedad y a querer controlarlo todo. Me quedo quieto y reconozco que tú eres Dios. Amén.",
 ["ansiedad", "fe"], ["paz", "quietud", "soberanía de Dios", "refugio"], ["ansiedad", "estrés", "control", "agitación"])

add("sal-91-14", "profetas", "Salmos 91:14-15", "Salmos", "Dios",
 "Por cuanto en mí ha puesto su voluntad, yo también lo libraré: pondrélo en alto, por cuanto ha conocido mi nombre. Me invocará, y yo le responderé: con él estaré yo en la angustia: lo libraré, y le glorificaré.",
 "Quien habita al abrigo del Altísimo", ["Moisés", "David"],
 "Salmo de protección, atribuido por la tradición a Moisés o a David. En los últimos versículos, Dios mismo toma la palabra.",
 "El salmo habla de peligros reales: el terror nocturno, la flecha de día, la pestilencia. La vida estaba llena de amenazas.",
 "El miedo al peligro, la enfermedad y la angustia.",
 "Dios no promete que nunca habrá angustia, sino que estará con nosotros en ella. Quien lo ama y lo invoca recibe su respuesta, su compañía y su liberación.",
 "Si hoy estás enfrentando miedo por tu salud, tu seguridad o tu familia, invoca a Dios por su nombre. No tienes que fingir que no hay peligro: Él promete estar contigo en medio de la angustia. Ora este salmo cada noche.",
 "Señor, pongo en ti mi amor y mi confianza. Hoy renuncio al miedo que me roba la paz. Tú prometiste responderme y estar conmigo en la angustia. Líbrame y guárdame. Amén.",
 ["miedo", "ansiedad"], ["protección", "refugio", "oración", "liberación"], ["miedo", "angustia", "enfermedad"])

add("2cr-7-14", "profetas", "2 Crónicas 7:14", "2 Crónicas", "Yavé",
 "Si se humillare mi pueblo, sobre los cuales mi nombre es invocado, y oraren, y buscaren mi rostro, y se volvieren de sus malos caminos; entonces yo oiré desde los cielos, y perdonaré sus pecados, y sanaré su tierra.",
 "El rey Salomón", ["Salomón"],
 "Hacia el año 960 a. C. Salomón acababa de dedicar el templo de Jerusalén con una gran oración y fiesta.",
 "Esa noche Yavé se le aparece para responder su oración, anticipando que el pueblo fallaría y necesitaría volver a Él.",
 "El alejamiento de Dios y las heridas que el pecado deja en un pueblo.",
 "Dios pone el camino de regreso en cuatro pasos: humillarse, orar, buscar su rostro y volverse de lo malo. Y responde con tres promesas: oír, perdonar y sanar. El perdón de Dios también restaura lo que se había dañado.",
 "Si hoy estás enfrentando las consecuencias de haberte alejado de Dios —en tu vida, tu familia o tu comunidad—, sigue estos cuatro pasos. Dedica hoy un tiempo a humillarte y orar con sinceridad. Dios promete sanar.",
 "Señor, me humillo delante de ti. Busco tu rostro y me vuelvo de mis malos caminos. Hoy renuncio al orgullo. Oye desde los cielos, perdona mi pecado y sana mi tierra, mi casa y mi corazón. Amén.",
 ["perdon", "esperanza"], ["arrepentimiento", "oración", "sanidad", "restauración"], ["pecado", "orgullo", "alejamiento de Dios"])

add("1re-19-9", "profetas", "1 Reyes 19:9, 18", "1 Reyes", "Yavé",
 "¿Qué haces aquí, Elías?… Y yo haré que queden en Israel siete mil; todas rodillas que no se encorvaron a Baal, y bocas todas que no lo besaron.",
 "El profeta Elías", ["Elías", "Jezabel", "Acab"],
 "Hacia el año 860 a. C., en tiempos del rey Acab y la reina Jezabel, que promovían el culto a Baal.",
 "Elías acababa de vencer a los profetas de Baal en el monte Carmelo, pero Jezabel juró matarlo. Huyó al desierto, deseó morir y se escondió en una cueva.",
 "El agotamiento, la depresión y la sensación de estar completamente solo.",
 "Dios primero cuida el cuerpo de Elías: le da comida y sueño. Luego le habla en un silbo apacible y le hace una pregunta. Finalmente le revela que no está solo: hay siete mil fieles. La soledad de Elías era real, pero no era toda la verdad.",
 "Si hoy estás enfrentando agotamiento o tristeza profunda después de un gran esfuerzo, cuida tu cuerpo: descansa, come, duerme. Luego escucha la voz suave de Dios. Y si la tristeza no se va, busca ayuda: no eres el único que sigue en pie.",
 "Señor, estoy agotado y me siento solo. Hoy renuncio a la mentira de que todo depende de mí y de que nadie más te es fiel. Háblame en tu silbo apacible y renueva mis fuerzas. Amén.",
 ["tristeza", "soledad"], ["depresión", "agotamiento", "voz de Dios", "descanso"], ["depresión", "agotamiento", "soledad", "tristeza"])

add("joe-2-25", "profetas", "Joel 2:25", "Joel", "Yavé",
 "Y os restituiré los años que comió la oruga, la langosta, el pulgón, y el revoltón; mi grande ejército que envié contra vosotros.",
 "El pueblo de Judá, por medio del profeta Joel", ["Joel"],
 "El profeta Joel habla a Judá después de una plaga de langostas devastadora, que se había convertido en imagen del juicio de Dios.",
 "Las cosechas estaban destruidas, los campos vacíos y el pueblo había perdido años de trabajo. Joel llamó al pueblo a volver a Dios con ayuno y llanto.",
 "El dolor por el tiempo perdido y las pérdidas que parecen irreparables.",
 "Dios promete algo imposible: devolver años. No solo detiene la plaga, sino que restituye lo que se perdió. Su restauración alcanza incluso el pasado.",
 "Si hoy estás enfrentando el dolor de años perdidos —por malas decisiones, una enfermedad, una relación o una crisis—, entrégale a Dios ese tiempo. Pídele que lo restituya y empieza hoy a sembrar de nuevo.",
 "Señor, siento que he perdido años que no volverán. Hoy renuncio a la amargura por el tiempo perdido. Tú puedes restituir lo que la langosta comió. Restáurame y hazme fructificar de nuevo. Amén.",
 ["esperanza", "tristeza"], ["restauración", "tiempo perdido", "nuevo comienzo"], ["pérdida", "arrepentimiento", "amargura"])

add("isa-6-8", "profetas", "Isaías 6:8", "Isaías", "Yavé",
 "¿A quién enviaré, y quién nos irá?",
 "El profeta Isaías", ["Isaías"],
 "Hacia el año 740 a. C., el año en que murió el rey Uzías. Isaías tiene una visión de Dios sentado en un trono alto en el templo.",
 "Ante la santidad de Dios, Isaías exclama «¡Ay de mí!», consciente de sus labios impuros. Un serafín toca su boca con un carbón encendido y le dice que su culpa ha sido quitada.",
 "La indiferencia ante la misión y la sensación de no ser digno de servir.",
 "Primero Dios limpia a Isaías; después pregunta. No exige perfección para servir, pero sí un corazón disponible. Isaías respondió: «Heme aquí, envíame a mí».",
 "Si hoy estás enfrentando la duda de si Dios podría usarte, recuerda que Él limpia antes de enviar. Pregúntale dónde quiere que sirvas esta semana —en tu casa, tu trabajo o tu iglesia— y responde como Isaías.",
 "Señor, tú me has limpiado. Hoy renuncio a sentirme indigno de servirte. Cuando preguntas «¿a quién enviaré?», quiero responder: heme aquí, envíame a mí. Amén.",
 ["obediencia"], ["llamado", "misión", "santidad", "servicio"], ["indiferencia", "sentirse indigno", "culpa"])

add("isa-1-18", "profetas", "Isaías 1:18", "Isaías", "Yavé",
 "Venid luego, dirá Yavé, y estemos a cuenta: si vuestros pecados fueren como la grana, como la nieve serán emblanquecidos: si fueren rojos como el carmesí, vendrán a ser como blanca lana.",
 "Judá y Jerusalén, por medio de Isaías", ["Isaías"],
 "Siglo VIII a. C. Judá cumplía con rituales religiosos, pero vivía en injusticia: se oprimía a huérfanos y viudas.",
 "Dios acusa al pueblo como en un juicio. Sus sacrificios y fiestas le cansaban porque sus manos estaban llenas de injusticia.",
 "La culpa profunda y la religión vacía que intenta cubrirla.",
 "En medio del juicio, Dios hace una invitación sorprendente: «venid y razonemos». El rojo intenso de la grana era un tinte imposible de quitar. Dios promete lo imposible: dejar blanco como la nieve lo que parecía manchado para siempre.",
 "Si hoy estás enfrentando una culpa que sientes imposible de borrar, acepta la invitación: ve a Dios y habla con Él con honestidad. No hay mancha demasiado profunda para su perdón. Confiesa y recibe su limpieza.",
 "Señor, mis pecados son como la grana. Hoy renuncio a la culpa que me dice que no tengo remedio. Acepto tu invitación. Emblanquéceme como la nieve y hazme nuevo. Amén.",
 ["culpa", "perdon"], ["perdón", "limpieza", "pecado", "justicia"], ["culpa", "vergüenza", "pecado"])

add("jer-1-5", "profetas", "Jeremías 1:5, 7-8", "Jeremías", "Yavé",
 "Antes que te formase en el vientre te conocí, y antes que salieses de la matriz te santifiqué, te di por profeta a las gentes… No digas, soy niño; porque a todo lo que te enviaré irás tú, y dirás todo lo que te mandaré. No temas delante de ellos, porque contigo soy para librarte, dice Yavé.",
 "El joven Jeremías", ["Jeremías"],
 "Hacia el año 627 a. C., en tiempos del rey Josías. Judá se acercaba a su momento más oscuro: la invasión de Babilonia.",
 "Jeremías era muy joven, hijo de sacerdotes de Anatot. Al oír el llamado, respondió: «¡Ah, Señor Yavé! He aquí, no sé hablar, porque soy niño».",
 "El miedo por la juventud, la inexperiencia y el temor al rechazo de la gente.",
 "Dios le dice a Jeremías que lo conocía antes de nacer. Su vida no fue un accidente: tenía propósito desde el vientre. Y ante su miedo, Dios no le promete que no habrá oposición, sino su presencia para librarlo.",
 "Si hoy estás enfrentando la sensación de ser demasiado joven, inexperto o insignificante, recuerda que Dios te conoció antes de que nacieras. Tu vida tiene propósito. Deja de decir «no puedo» y pregúntale: «¿a dónde me envías?».",
 "Señor, tú me conociste antes de formarme. Hoy renuncio al miedo y a la excusa de mi debilidad. Envíame, pon tus palabras en mi boca y sé conmigo para librarme. Amén.",
 ["miedo", "obediencia"], ["propósito", "identidad", "llamado", "vida antes de nacer"], ["miedo", "inseguridad", "inexperiencia"])

add("jer-31-3", "profetas", "Jeremías 31:3", "Jeremías", "Yavé",
 "Con amor eterno te he amado; por tanto te soporté con misericordia.",
 "Israel, el pueblo disperso", ["Jeremías"],
 "Jeremías profetizó durante la caída de Jerusalén. Los capítulos 30 al 33 se conocen como el «Libro de la consolación».",
 "El pueblo había sido infiel durante siglos y enfrentaba el exilio. Muchos pensaban que Dios los había desechado para siempre.",
 "La sensación de no ser amado y el miedo a haber agotado la paciencia de Dios.",
 "Dios declara que su amor no depende del comportamiento del pueblo: es un amor eterno. Porque los ama así, los ha atraído y sostenido con misericordia, incluso durante su infidelidad.",
 "Si hoy estás enfrentando la sensación de no ser amado o de haber decepcionado a Dios demasiadas veces, lee esta frase con tu nombre. Su amor por ti no empezó cuando lo merecías y no terminará cuando falles.",
 "Señor, me cuesta creer que me amas así. Hoy renuncio a la mentira de que tu amor se ha agotado. Tú me amas con amor eterno. Atráeme a ti con tu misericordia. Amén.",
 ["amor", "tristeza"], ["amor de Dios", "misericordia", "fidelidad", "identidad"], ["sentirse no amado", "rechazo", "culpa"])

add("jer-33-3", "profetas", "Jeremías 33:3", "Jeremías", "Yavé",
 "Clama a mí, y te responderé, y te enseñaré cosas grandes y dificultosas que tú no sabes.",
 "Jeremías, preso en el patio de la cárcel", ["Jeremías"],
 "Hacia el año 587 a. C. El ejército babilonio sitiaba Jerusalén y la caída de la ciudad era inminente.",
 "Jeremías estaba encarcelado por el rey Sedequías por anunciar la verdad. Desde la prisión, Dios le habla por segunda vez.",
 "La desesperanza ante circunstancias cerradas y la sensación de que no hay salida.",
 "Encerrado y con la ciudad a punto de caer, Jeremías recibe una invitación: clamar. Dios promete responder y revelar cosas que él no podía imaginar. Las circunstancias estaban cerradas, pero el cielo no.",
 "Si hoy estás enfrentando una situación que te tiene «preso» —una enfermedad, una deuda, una espera—, no dejes de clamar. Dedica un tiempo cada día a orar por ello y a escuchar. Dios puede mostrarte salidas que hoy no ves.",
 "Señor, clamo a ti desde mi encierro. Hoy renuncio a la desesperanza. Respóndeme y enséñame las cosas grandes que no sé. Abre caminos donde yo solo veo muros. Amén.",
 ["fe", "esperanza"], ["oración", "revelación", "respuesta de Dios"], ["desesperanza", "encierro", "ansiedad"])

# ---------------------------------------------------------------- ISRAEL (exilio y regreso)
add("jer-29-11", "israel", "Jeremías 29:11-13", "Jeremías", "Yavé",
 "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Yavé, pensamientos de paz, y no de mal, para daros el fin que esperáis. Entonces me invocaréis, e iréis y oraréis a mí, y yo os oiré: y me buscaréis y hallaréis, porque me buscaréis de todo vuestro corazón.",
 "Los judíos deportados en Babilonia", ["Jeremías"],
 "Hacia el año 597 a. C. Nabucodonosor había llevado cautivos a Babilonia a miles de habitantes de Jerusalén. Jeremías les envía una carta.",
 "Los exiliados esperaban volver pronto, pero Dios les anuncia que el exilio duraría setenta años. Debían edificar casas, plantar huertos y buscar la paz de la ciudad donde estaban.",
 "La desesperanza de vivir en una situación que no se elegía y que no terminaría pronto.",
 "Esta famosa promesa fue dada a personas que no verían un cambio rápido. Dios no niega la dificultad, pero les asegura que sus planes son de paz y que el final será bueno. Mientras tanto, los invita a buscarlo de todo corazón.",
 "Si hoy estás enfrentando una situación larga que no elegiste, no vivas solo esperando que termine. Construye, siembra y busca a Dios donde estás. Sus pensamientos hacia ti son de paz, aunque el proceso tarde.",
 "Señor, estoy en un lugar que no elegí. Hoy renuncio a la desesperanza y a la impaciencia. Creo que tus pensamientos sobre mí son de paz. Te busco de todo corazón, y sé que te hallaré. Amén.",
 ["esperanza", "fe"], ["futuro", "planes de Dios", "exilio", "paciencia"], ["desesperanza", "impaciencia", "incertidumbre"])

add("eze-36-26", "israel", "Ezequiel 36:26", "Ezequiel", "Yavé",
 "Y os daré corazón nuevo, y pondré espíritu nuevo dentro de vosotros; y quitaré de vuestra carne el corazón de piedra, y os daré corazón de carne.",
 "Israel en el exilio, por medio de Ezequiel", ["Ezequiel"],
 "Ezequiel era sacerdote y profeta entre los exiliados en Babilonia, junto al río Quebar, hacia el año 586 a. C.",
 "Jerusalén y su templo habían sido destruidos. El pueblo cargaba con la vergüenza de su historia de infidelidad.",
 "El corazón endurecido que ya no puede cambiar por sí mismo.",
 "Dios no le pide al pueblo que se fabrique un corazón nuevo: promete dárselo. Cambiará la dureza por sensibilidad y pondrá su propio Espíritu dentro de ellos. La transformación verdadera es un regalo de Dios.",
 "Si hoy estás enfrentando la frustración de no poder cambiar —hábitos, reacciones, frialdad espiritual—, deja de intentarlo solo con fuerza de voluntad. Pídele a Dios que haga en ti lo que prometió: un corazón nuevo.",
 "Señor, mi corazón se ha endurecido. Hoy renuncio a intentar cambiar solo con mis fuerzas. Quita mi corazón de piedra y dame un corazón de carne. Pon tu Espíritu dentro de mí. Amén.",
 ["esperanza", "culpa"], ["transformación", "corazón nuevo", "Espíritu", "restauración"], ["dureza de corazón", "frialdad espiritual", "hábitos"])

add("isa-41-10", "israel", "Isaías 41:10", "Isaías", "Yavé",
 "No temas, que yo soy contigo; no desmayes, que yo soy tu Dios que te esfuerzo: siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.",
 "Israel, «mi siervo», en tiempos de exilio", ["Isaías", "Israel"],
 "Los capítulos 40 al 55 de Isaías son palabras de consuelo para el pueblo que viviría el exilio en Babilonia, en el siglo VI a. C.",
 "Las naciones temblaban ante el avance de un nuevo conquistador. Israel, pequeño y derrotado, se sentía indefenso.",
 "El miedo, la debilidad y la sensación de estar a punto de desmayar.",
 "Dios da cinco promesas en un solo versículo: estoy contigo, soy tu Dios, te esfuerzo, te ayudo y te sostengo. La mano derecha era símbolo de fuerza: Dios sostiene a su pueblo con su mano más fuerte.",
 "Si hoy estás enfrentando miedo o sientes que te faltan las fuerzas, repite estas cinco promesas despacio, una por una. Cuando llegue la ansiedad, imagina la mano de Dios sosteniéndote.",
 "Señor, hoy renuncio al miedo y al desmayo. Tú estás conmigo, eres mi Dios, me das fuerzas, me ayudas y me sostienes con tu mano. Me apoyo en ti. Amén.",
 ["miedo", "ansiedad", "fe"], ["fortaleza", "presencia de Dios", "ayuda", "protección"], ["miedo", "debilidad", "ansiedad", "desánimo"])

add("isa-43-1", "israel", "Isaías 43:1-2", "Isaías", "Yavé",
 "No temas, porque yo te redimí; te puse nombre, mío eres tú. Cuando pasares por las aguas, yo seré contigo; y por los ríos, no te anegarán. Cuando pasares por el fuego, no te quemarás, ni la llama arderá en ti.",
 "Jacob e Israel, el pueblo formado por Dios", ["Israel", "Jacob"],
 "Palabras de consuelo para el pueblo en el exilio. Dios se presenta como su Creador y Formador.",
 "El pueblo había pasado por el «agua» y el «fuego» de la guerra, la deportación y la pérdida. Se sentía olvidado.",
 "El miedo a las pruebas y la soledad de atravesarlas.",
 "Dios no dice «si pasas», sino «cuando pases» por las aguas y el fuego. Las pruebas llegarán, pero no nos destruirán, porque Él pasará con nosotros. Y nos recuerda nuestra identidad: «te puse nombre, mío eres tú».",
 "Si hoy estás enfrentando una prueba que te ahoga o te quema, escucha: no estás solo en ella. Di en voz alta tu nombre y añade: «soy de Dios». Él atraviesa contigo este río.",
 "Señor, estoy pasando por aguas profundas. Hoy renuncio al miedo y a la soledad. Tú me redimiste, me llamaste por mi nombre y soy tuyo. Pasa conmigo por este río y este fuego. Amén.",
 ["miedo", "soledad"], ["identidad", "pruebas", "presencia de Dios", "redención"], ["miedo", "soledad", "pruebas"])

add("isa-43-18", "israel", "Isaías 43:18-19", "Isaías", "Yavé",
 "No os acordéis de las cosas pasadas, ni traigáis a memoria las cosas antiguas. He aquí que yo hago cosa nueva: presto saldrá a luz: ¿no la sabréis? Otra vez pondré camino en el desierto, y ríos en la soledad.",
 "Israel en el exilio", ["Israel"],
 "Dios acababa de recordar el éxodo, cuando abrió camino en el mar. Ahora anuncia un nuevo éxodo: el regreso desde Babilonia.",
 "El pueblo vivía mirando atrás: a sus glorias perdidas y a sus fracasos. Le costaba imaginar un futuro distinto.",
 "Vivir atado al pasado, ya sea por nostalgia o por culpa.",
 "Dios pide dejar de mirar atrás, no porque el pasado no importe, sino porque Él está haciendo algo nuevo. Donde hay desierto, abrirá camino; donde hay soledad, hará brotar ríos.",
 "Si hoy estás enfrentando un pasado que te pesa —errores, heridas o «tiempos mejores»—, pídele a Dios ojos para ver lo nuevo que está haciendo. Anota una señal de vida nueva que veas esta semana.",
 "Señor, hoy renuncio a vivir atado a mi pasado. Tú haces cosas nuevas. Abre camino en mi desierto y ríos en mi soledad. Dame ojos para ver lo que ya estás haciendo. Amén.",
 ["esperanza", "culpa"], ["nuevo comienzo", "pasado", "futuro", "restauración"], ["culpa", "nostalgia", "estancamiento"])

add("isa-43-25", "israel", "Isaías 43:25", "Isaías", "Yavé",
 "Yo, yo soy el que borro tus rebeliones por amor de mí; y no me acordaré de tus pecados.",
 "Israel", ["Israel", "Jacob"],
 "En el mismo discurso de consuelo a los exiliados, Dios recuerda al pueblo cómo lo habían cansado con sus pecados.",
 "Israel no había honrado a Dios; en lugar de ofrendas, le había traído pecados. Merecía el rechazo.",
 "La culpa que se recuerda una y otra vez y no deja vivir en paz.",
 "Dios repite «yo, yo» para dejar claro que el perdón es obra suya y nace de su propio amor, no de los méritos del pueblo. Y hace una promesa asombrosa: no se acordará más de esos pecados.",
 "Si hoy estás enfrentando el recuerdo constante de tus errores, recuerda que Dios ha decidido no recordarlos. Cuando tu mente vuelva a acusarte, responde: «Dios lo borró». Deja de desenterrar lo que Él perdonó.",
 "Señor, tú borras mis rebeliones por amor. Hoy renuncio a la culpa que sigue acusándome. Si tú no te acuerdas de mis pecados, yo tampoco viviré atado a ellos. Gracias por tu perdón. Amén.",
 ["culpa", "perdon"], ["perdón", "gracia", "olvido de Dios", "pecado"], ["culpa", "remordimiento", "autocondena"])

add("isa-49-15", "israel", "Isaías 49:15", "Isaías", "Yavé",
 "¿Olvidaráse la mujer de lo que parió, para dejar de compadecerse del hijo de su vientre? Aunque se olviden ellas, yo no me olvidaré de ti.",
 "Sion (Jerusalén), que se sentía abandonada", ["Israel"],
 "Palabras a Jerusalén durante el exilio, cuando la ciudad estaba en ruinas y sus habitantes deportados.",
 "Sion había dicho: «Me dejó Yavé, y el Señor se olvidó de mí». Dios responde a esa queja.",
 "El abandono y la sensación de haber sido olvidado por Dios.",
 "Dios usa la imagen del amor más fuerte que conocemos: el de una madre por su bebé. Y dice que su amor es aún más firme. En el versículo siguiente añade: «en las palmas te tengo esculpida».",
 "Si hoy estás enfrentando abandono —de tu familia, tu pareja o tus amigos— o sientes que Dios se olvidó de ti, lee esta promesa despacio. Aunque otros se olviden, Él no. Mira tus manos y recuerda que tu nombre está escrito en las suyas.",
 "Señor, me he sentido olvidado. Hoy renuncio a la mentira del abandono. Tu amor es más fiel que el de una madre. Tú no te olvidas de mí; me tienes grabado en tus manos. Amén.",
 ["soledad", "amor"], ["amor de Dios", "abandono", "fidelidad", "maternidad"], ["abandono", "soledad", "rechazo"])

add("isa-55-8", "israel", "Isaías 55:8-9", "Isaías", "Yavé",
 "Porque mis pensamientos no son vuestros pensamientos, ni vuestros caminos mis caminos, dijo Yavé. Como son más altos los cielos que la tierra, así son mis caminos más altos que vuestros caminos, y mis pensamientos más que vuestros pensamientos.",
 "Todo el que tenga sed, en Israel y las naciones", ["Isaías"],
 "Final de las palabras de consolación. Dios invita a todos a venir a Él gratuitamente, como a un banquete.",
 "El pueblo no entendía cómo Dios podía perdonar tan ampliamente ni por qué sus planes eran tan distintos de lo esperado.",
 "La frustración cuando la vida no sale como planeamos y no entendemos a Dios.",
 "Dios no pide que entendamos todo, sino que confiemos en que su perspectiva es más alta. En el versículo anterior acaba de hablar de su amplio perdón: incluso su misericordia supera nuestra lógica.",
 "Si hoy estás enfrentando una situación que no tiene sentido para ti, reconoce que tu vista es limitada. Escribe lo que no entiendes y, al lado, escribe: «Tus caminos son más altos». Suelta la necesidad de comprenderlo todo hoy.",
 "Señor, no entiendo tus caminos. Hoy renuncio a exigir que todo tenga sentido para mí. Tus pensamientos son más altos que los míos. Confío en ti aunque no vea el cuadro completo. Amén.",
 ["fe"], ["soberanía de Dios", "planes de Dios", "confianza", "sabiduría"], ["frustración", "confusión", "control"])

add("zac-4-6", "israel", "Zacarías 4:6", "Zacarías", "Yavé",
 "No con ejército, ni con fuerza, sino con mi espíritu, ha dicho Yavé de los ejércitos.",
 "Zorobabel, gobernador de Judá", ["Zorobabel", "Zacarías"],
 "Hacia el año 520 a. C. Un grupo de judíos había regresado del exilio a Jerusalén para reconstruir el templo.",
 "La obra estaba detenida desde hacía años por la oposición de los vecinos, la pobreza y el desánimo. Zorobabel tenía pocos recursos.",
 "El desánimo ante una tarea demasiado grande para los recursos disponibles.",
 "Dios le recuerda a Zorobabel que la obra no depende de ejércitos, dinero ni fuerza humana, sino de su Espíritu. Lo que parecía un «gran monte» se convertiría en llanura.",
 "Si hoy estás enfrentando un proyecto, una familia o un ministerio que te supera, deja de medirlo solo por tus recursos. Haz tu parte con fidelidad y ora cada día pidiendo que el Espíritu de Dios haga lo que tú no puedes.",
 "Señor, mis fuerzas no alcanzan. Hoy renuncio al desánimo y a confiar solo en lo que tengo. No con ejército ni con fuerza, sino con tu Espíritu. Haz tu obra en mí y a través de mí. Amén.",
 ["fe"], ["Espíritu Santo", "reconstrucción", "recursos", "dependencia de Dios"], ["desánimo", "falta de recursos", "agotamiento"])

add("mal-3-6", "israel", "Malaquías 3:6-7", "Malaquías", "Yavé",
 "Porque yo Yavé, no me mudo; y así vosotros, hijos de Jacob, no habéis sido consumidos… Tornaos a mí, y yo me tornaré a vosotros, ha dicho Yavé de los ejércitos.",
 "El pueblo de Judá después del regreso", ["Malaquías"],
 "Hacia el año 430 a. C. Es el último profeta del Antiguo Testamento. Después vendrían cuatrocientos años de silencio profético.",
 "El templo ya estaba reconstruido, pero el pueblo había caído en la rutina, la indiferencia y el cinismo religioso.",
 "La tibieza espiritual y el alejamiento gradual de Dios.",
 "La fidelidad inmutable de Dios es la razón por la que su pueblo sigue en pie. Aunque ellos cambiaron, Él no. Y la invitación es sencilla y recíproca: «volved a mí y yo volveré a vosotros».",
 "Si hoy estás enfrentando frialdad espiritual o sientes que te fuiste alejando poco a poco, no necesitas un gran discurso: solo volver. Da hoy un paso concreto de regreso: una oración sincera, una lectura, una conversación con alguien de fe.",
 "Yavé, tú no cambias. Aunque yo me he alejado, tú sigues siendo fiel. Hoy renuncio a la tibieza. Me vuelvo a ti, y creo que tú te vuelves a mí. Amén.",
 ["perdon", "esperanza"], ["fidelidad de Dios", "arrepentimiento", "regreso", "inmutabilidad"], ["tibieza", "alejamiento de Dios", "rutina"])
