# ---------------------------------------------------------------- EVANGELIOS
add("mat-3-17", "evangelios", "Mateo 3:17", "Mateo", "La voz del Padre",
 "Este es mi Hijo amado, en el cual tengo contentamiento.",
 "Jesús y los presentes en su bautismo", ["Jesús", "Juan el Bautista"],
 "Hacia el año 27 d. C., en el río Jordán. Tras cuatrocientos años de silencio profético, Dios vuelve a hablar desde el cielo.",
 "Jesús, antes de empezar su ministerio público, fue bautizado por Juan. Al salir del agua, el Espíritu descendió como paloma y se oyó la voz del Padre.",
 "La necesidad de identidad y aprobación que no dependa de lo que uno logra.",
 "El Padre declara su amor y su agrado por Jesús antes de que Él haga un solo milagro. La identidad viene antes que la misión. En Cristo, los creyentes también son hijos amados.",
 "Si hoy estás enfrentando la presión de demostrar tu valor con logros o la necesidad de aprobación, escucha esta voz. En Cristo, Dios te llama hijo amado antes de que hagas nada. Empieza tu día desde esa identidad, no para conseguirla.",
 "Padre, gracias porque en Cristo me llamas hijo amado. Hoy renuncio a buscar mi valor en mis logros o en la aprobación de otros. Descanso en tu amor y vivo desde él. Amén.",
 ["amor", "fe"], ["identidad", "bautismo", "Trinidad", "aprobación"], ["necesidad de aprobación", "inseguridad", "perfeccionismo"])

add("mat-6-34", "evangelios", "Mateo 6:34", "Mateo", "Jesús",
 "Así que, no os congojéis por el día de mañana; que el día de mañana traerá su fatiga: basta al día su afán.",
 "Los discípulos y la multitud en el Sermón del Monte", ["Jesús", "discípulos"],
 "Galilea, al inicio del ministerio de Jesús. En el Sermón del Monte enseña cómo vivir en el reino de Dios.",
 "Jesús hablaba a gente sencilla preocupada por lo básico: qué comer, qué beber, con qué vestirse. Les señala las aves y los lirios.",
 "La ansiedad por el futuro y por las necesidades materiales.",
 "Jesús no dice que el mañana no tendrá problemas, sino que no debemos cargarlos hoy. El versículo anterior da la clave: buscar primero el reino de Dios, y el Padre, que conoce nuestras necesidades, proveerá.",
 "Si hoy estás enfrentando ansiedad por el futuro —dinero, salud, trabajo—, pregúntate: ¿qué me toca hacer hoy? Haz solo eso y entrega el resto a Dios. Cuando tu mente salte a mañana, vuelve con suavidad al día de hoy.",
 "Señor, hoy renuncio a la ansiedad por el mañana. Tú conoces lo que necesito. Ayúdame a vivir este día contigo, a buscar primero tu reino y a confiar en que mañana también estarás. Amén.",
 ["ansiedad"], ["preocupación", "provisión", "futuro", "reino de Dios"], ["ansiedad", "preocupación", "estrés", "miedo al futuro"])

add("mat-11-28", "evangelios", "Mateo 11:28-29", "Mateo", "Jesús",
 "Venid a mí todos los que estáis trabajados y cargados, que yo os haré descansar. Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón; y hallaréis descanso para vuestras almas.",
 "Las multitudes cansadas", ["Jesús"],
 "Galilea. Los líderes religiosos habían convertido la fe en una carga de reglas imposibles de cumplir.",
 "Muchos rechazaban a Jesús. Él agradece al Padre por revelarse a los sencillos y hace esta invitación abierta a todos.",
 "El agotamiento físico, emocional y espiritual; la religión como carga pesada.",
 "Jesús no ofrece más reglas, sino a sí mismo. El yugo era la pieza que unía a dos bueyes para compartir la carga. Jesús invita a caminar unido a Él, que es manso y humilde, y encontrar descanso para el alma.",
 "Si hoy estás enfrentando cansancio, estrés o una fe que se ha vuelto pesada, acepta esta invitación literalmente. Detente, dile a Jesús qué te está cansando y entrégale esa carga. Aprende de su mansedumbre: baja el ritmo.",
 "Jesús, vengo a ti cansado y cargado. Hoy renuncio al peso que llevo solo. Tomo tu yugo y aprendo de ti. Dame el descanso que mi alma necesita. Amén.",
 ["ansiedad", "tristeza"], ["descanso", "cansancio", "gracia", "mansedumbre"], ["agotamiento", "estrés", "ansiedad", "legalismo"])

add("mat-14-27", "evangelios", "Mateo 14:27", "Mateo", "Jesús",
 "Confiad, yo soy; no tengáis miedo.",
 "Los discípulos, en la barca", ["Pedro", "discípulos"],
 "Mar de Galilea, poco después de la multiplicación de los panes y los peces.",
 "De madrugada, los discípulos remaban contra el viento en medio de las olas. Vieron a Jesús caminando sobre el agua y, aterrados, gritaron creyendo que era un fantasma.",
 "El miedo en medio de la tormenta y ante lo que no se entiende.",
 "Jesús dice «yo soy», las mismas palabras con que Dios se presentó a Moisés. Su presencia cambia el significado de la tormenta. Después, Pedro caminó sobre el agua mientras miró a Jesús.",
 "Si hoy estás enfrentando una tormenta que te llena de miedo, escucha la voz de Jesús en medio de ella: «Yo soy». Cuando te hundas en la preocupación, haz como Pedro: clama «¡Señor, sálvame!» y vuelve a fijar la mirada en Él.",
 "Jesús, en medio de mis olas te escucho decir: «Yo soy». Hoy renuncio al miedo. Aunque el viento sea contrario, tú estás aquí. Tómame de la mano cuando me hunda. Amén.",
 ["miedo", "fe"], ["tormentas", "presencia de Jesús", "milagros", "fe"], ["miedo", "pánico", "crisis"])

add("mat-17-5", "evangelios", "Mateo 17:5", "Mateo", "La voz del Padre",
 "Este es mi Hijo amado, en el cual tomo contentamiento: a él oíd.",
 "Pedro, Jacobo y Juan, en el monte de la transfiguración", ["Pedro", "Jacobo", "Juan", "Moisés", "Elías"],
 "Poco antes de ir a Jerusalén a morir, Jesús sube a un monte alto con tres discípulos.",
 "Jesús se transfiguró: su rostro brilló como el sol. Aparecieron Moisés y Elías hablando con Él. Pedro, sin saber qué decir, propuso hacer tres tiendas. Entonces una nube de luz los cubrió.",
 "La confusión y las muchas voces que compiten por nuestra atención.",
 "El Padre interrumpe a Pedro y pone a Jesús por encima de Moisés (la ley) y Elías (los profetas). Todo lo que Dios había dicho apunta a Él. La instrucción es simple: escuchadle.",
 "Si hoy estás enfrentando confusión por tantas opiniones y voces, haz de esta frase tu criterio: «a Él oíd». Dedica tiempo a leer las palabras de Jesús en los Evangelios y deja que su voz tenga la última palabra.",
 "Padre, hay muchas voces a mi alrededor. Hoy renuncio a la confusión. Quiero escuchar a tu Hijo amado por encima de todo. Enséñame a oírle y a obedecerle. Amén.",
 ["obediencia", "fe"], ["escuchar a Jesús", "transfiguración", "gloria"], ["confusión", "distracción", "miedo"])

add("mat-18-22", "evangelios", "Mateo 18:22", "Mateo", "Jesús",
 "No te digo hasta siete, mas aun hasta setenta veces siete.",
 "El apóstol Pedro", ["Pedro"],
 "Galilea. Jesús enseñaba a sus discípulos sobre la vida en comunidad y la restauración de los que fallan.",
 "Pedro preguntó cuántas veces debía perdonar a su hermano, proponiendo siete, que ya parecía generoso. Los rabinos enseñaban perdonar tres veces.",
 "El perdón limitado, que lleva la cuenta de las ofensas.",
 "Jesús responde que el perdón no se cuenta. Luego cuenta la parábola del siervo al que se le perdonó una deuda enorme pero no perdonó una pequeña. Quien ha sido perdonado por Dios aprende a perdonar sin llevar la cuenta.",
 "Si hoy estás enfrentando la dificultad de perdonar a alguien que te ha herido muchas veces, recuerda cuánto te ha perdonado Dios. Perdonar no significa permitir el abuso ni dejar de poner límites, sino soltar la deuda delante de Dios.",
 "Señor, estoy cansado de perdonar. Hoy renuncio a llevar la cuenta de las ofensas. Recuerdo cuánto me has perdonado tú. Dame un corazón que perdone como el tuyo. Amén.",
 ["perdon", "amor"], ["perdón", "relaciones", "gracia", "comunidad"], ["rencor", "resentimiento", "ofensas repetidas"])

add("jua-8-11", "evangelios", "Juan 8:11", "Juan", "Jesús",
 "Ni yo te condeno: vete, y no peques más.",
 "Una mujer sorprendida en adulterio", ["mujer adúltera", "fariseos", "escribas"],
 "En el templo de Jerusalén. Los escribas y fariseos buscaban una excusa para acusar a Jesús.",
 "Trajeron a una mujer sorprendida en adulterio y la pusieron en medio, diciendo que la ley mandaba apedrearla. Jesús dijo: «El que de vosotros esté sin pecado, arroje contra ella la piedra el primero». Uno a uno se fueron.",
 "La culpa pública, la vergüenza y la condenación.",
 "Jesús, el único sin pecado que podía tirar la piedra, no la condena. Pero tampoco ignora el pecado: la envía a una vida nueva. El perdón viene primero; el cambio es la respuesta al perdón.",
 "Si hoy estás enfrentando culpa o vergüenza por algo que otros saben o que solo tú conoces, escucha a Jesús decirte: «ni yo te condeno». Recibe ese perdón y da hoy un paso concreto para alejarte de aquello que te dañaba.",
 "Jesús, tú eras el único que podía condenarme y no lo hiciste. Hoy renuncio a la culpa y a la vergüenza. Recibo tu perdón y, con tu ayuda, me voy a vivir una vida nueva. Amén.",
 ["culpa", "perdon"], ["perdón", "gracia", "condenación", "nueva vida"], ["culpa", "vergüenza", "condenación"])

add("jua-11-25", "evangelios", "Juan 11:25-26", "Juan", "Jesús",
 "Yo soy la resurrección y la vida: el que cree en mí, aunque esté muerto, vivirá. Y todo aquel que vive y cree en mí, no morirá eternamente.",
 "Marta, hermana de Lázaro", ["Marta", "María", "Lázaro"],
 "Betania, cerca de Jerusalén, poco antes de la última Pascua de Jesús.",
 "Lázaro, amigo de Jesús, llevaba cuatro días muerto. Marta salió a recibir a Jesús y le dijo: «Si hubieses estado aquí, mi hermano no fuera muerto».",
 "El duelo, la tristeza por la muerte y la pregunta de por qué Dios no llegó a tiempo.",
 "Jesús no le da a Marta una explicación, sino una persona: Él mismo. La resurrección no es solo un evento futuro, es Jesús. Poco después lloró con ellas y resucitó a Lázaro.",
 "Si hoy estás enfrentando la muerte de alguien que amas o el miedo a la muerte, lleva tu dolor a Jesús, como Marta. Él llora contigo y tiene la última palabra sobre la muerte. Permítete llorar y a la vez aferrarte a su promesa.",
 "Jesús, tú eres la resurrección y la vida. Hoy traigo mi duelo ante ti. Renuncio a la desesperanza frente a la muerte. Llora conmigo y dame la esperanza de la vida eterna. Amén.",
 ["tristeza", "esperanza", "fe"], ["muerte", "resurrección", "duelo", "vida eterna"], ["duelo", "tristeza", "miedo a la muerte", "pérdida"])

add("jua-12-28", "evangelios", "Juan 12:28", "Juan", "La voz del Padre",
 "Y lo he glorificado, y lo glorificaré otra vez.",
 "Jesús y la multitud en Jerusalén", ["Jesús", "Felipe", "Andrés"],
 "Jerusalén, en los días previos a la crucifixión. Unos griegos habían pedido ver a Jesús.",
 "Jesús anunció que su hora había llegado y que, como el grano de trigo, debía morir para dar fruto. Dijo: «Ahora está turbada mi alma… Padre, glorifica tu nombre». Entonces vino una voz del cielo.",
 "La angustia ante el sufrimiento que se acerca.",
 "Jesús confiesa su angustia, pero elige el propósito del Padre. El Padre responde confirmando que su gloria se manifestará también en la cruz y la resurrección. El dolor entregado a Dios no es en vano.",
 "Si hoy estás enfrentando angustia ante algo difícil que no puedes evitar, ora como Jesús: sé honesto con tu turbación y luego pídele a Dios que se glorifique en ello. Tu dolor puede convertirse en semilla.",
 "Padre, mi alma está turbada. Hoy renuncio a huir de tu propósito. Glorifica tu nombre en mi vida, aun en lo que me duele. Haz de mi dolor una semilla que dé fruto. Amén.",
 ["fe", "ansiedad"], ["gloria de Dios", "sufrimiento", "propósito", "cruz"], ["angustia", "miedo al sufrimiento"])

add("jua-13-34", "evangelios", "Juan 13:34", "Juan", "Jesús",
 "Un mandamiento nuevo os doy: Que os améis unos a otros: como os he amado, que también os améis los unos a los otros.",
 "Los doce discípulos, en la última cena", ["discípulos", "Pedro", "Juan", "Judas"],
 "Jerusalén, la noche antes de la crucifixión, durante la cena de Pascua.",
 "Jesús acababa de lavar los pies de sus discípulos, incluido Judas, que salió para traicionarlo. Sabiendo que se iba, les deja su mandamiento.",
 "El egoísmo, la división y el amor condicionado.",
 "Lo nuevo del mandamiento es la medida: «como yo os he amado». Un amor que sirve, lava pies, perdona y da la vida. Jesús añadió que en este amor todos conocerían que son sus discípulos.",
 "Si hoy estás enfrentando relaciones difíciles o una comunidad dividida, piensa en cómo te ha amado Jesús. Elige hoy un acto concreto de servicio humilde hacia alguien, especialmente hacia quien te cuesta amar.",
 "Jesús, tú me amaste hasta el fin. Hoy renuncio al egoísmo y al amor que pone condiciones. Enséñame a amar como tú me amas, sirviendo con humildad. Amén.",
 ["amor", "obediencia"], ["amor", "mandamiento", "servicio", "comunidad"], ["egoísmo", "división", "falta de amor"])

add("jua-14-27", "evangelios", "Juan 14:27", "Juan", "Jesús",
 "La paz os dejo, mi paz os doy: no como el mundo la da, yo os la doy. No se turbe vuestro corazón, ni tenga miedo.",
 "Los discípulos, en la última cena", ["discípulos", "Tomás", "Felipe"],
 "La misma noche de la última cena. Jesús se despide de sus discípulos y les promete el Espíritu Santo.",
 "Los discípulos estaban confundidos y temerosos: Jesús anunciaba que se iba, que uno lo traicionaría y que Pedro lo negaría.",
 "La turbación del corazón y el miedo ante un futuro incierto.",
 "Jesús deja como herencia su propia paz. No es la paz del mundo, que depende de que todo vaya bien, sino una paz que permanece en medio de la tormenta, porque se basa en su presencia.",
 "Si hoy estás enfrentando turbación o miedo, recuerda que la paz de Jesús no depende de tus circunstancias. Cierra los ojos, respira y recíbela como un regalo: «mi paz te doy». Repítelo cuando el miedo vuelva.",
 "Jesús, recibo tu paz. Hoy renuncio a la turbación de mi corazón y al miedo. No busco la paz del mundo, sino la tuya, que permanece aunque todo cambie. Amén.",
 ["ansiedad", "miedo"], ["paz", "Espíritu Santo", "despedida", "promesa"], ["ansiedad", "miedo", "turbación"])

add("luc-23-43", "evangelios", "Lucas 23:43", "Lucas", "Jesús",
 "De cierto te digo, que hoy estarás conmigo en el paraíso.",
 "Uno de los malhechores crucificados junto a Jesús", ["ladrón en la cruz"],
 "Monte Calvario, en las afueras de Jerusalén. Jesús fue crucificado entre dos malhechores.",
 "Uno de ellos se burlaba de Jesús. El otro lo reprendió, reconoció su culpa y dijo: «Acuérdate de mí cuando vinieres a tu reino».",
 "La culpa de una vida entera y la creencia de que ya es demasiado tarde.",
 "Aquel hombre no tenía tiempo de enmendar nada, solo de confiar. Jesús, en su propia agonía, le da la promesa más grande: «hoy, conmigo». Nunca es demasiado tarde para volverse a Dios.",
 "Si hoy estás enfrentando la sensación de que tu vida está demasiado torcida o de que es tarde para ti o para alguien que amas, recuerda al ladrón en la cruz. Dile a Jesús con sencillez: «acuérdate de mí».",
 "Jesús, acuérdate de mí. Hoy renuncio a la mentira de que es demasiado tarde. No traigo méritos, solo mi confianza en ti. Gracias por tu promesa de estar contigo. Amén.",
 ["culpa", "esperanza", "perdon"], ["salvación", "gracia", "cruz", "paraíso"], ["culpa", "desesperanza", "arrepentimiento tardío"])

add("jua-21-17", "evangelios", "Juan 21:17", "Juan", "Jesús resucitado",
 "Simón, hijo de Jonás, ¿me amas?… Apacienta mis ovejas.",
 "El apóstol Pedro", ["Pedro"],
 "Junto al mar de Tiberíades (Galilea), después de la resurrección. Jesús había preparado un desayuno para sus discípulos.",
 "Pedro había negado a Jesús tres veces la noche de su arresto. Ahora Jesús le pregunta tres veces si lo ama. Pedro se entristece.",
 "La culpa por haber fallado a quien más se ama y la sensación de estar descalificado.",
 "A cada negación corresponde una pregunta de amor y una nueva comisión. Jesús no le echa en cara su fracaso: lo restaura y le devuelve su misión. El fracaso no es el final para quien ama a Jesús.",
 "Si hoy estás enfrentando la culpa de haber fallado a Dios o a alguien importante, deja que Jesús te haga su pregunta: «¿me amas?». Respóndele con sinceridad y acepta que Él todavía tiene un propósito para ti.",
 "Jesús, te he fallado, pero tú sabes que te amo. Hoy renuncio a la culpa que me descalifica. Restáurame como a Pedro y dame de nuevo un propósito para servirte. Amén.",
 ["culpa", "perdon", "amor"], ["restauración", "fracaso", "amor", "misión"], ["culpa", "fracaso", "vergüenza"])

add("mat-28-20", "evangelios", "Mateo 28:20", "Mateo", "Jesús resucitado",
 "…enseñándoles que guarden todas las cosas que os he mandado: y he aquí, yo estoy con vosotros todos los días, hasta el fin del mundo.",
 "Los once discípulos, en un monte de Galilea", ["discípulos"],
 "Después de la resurrección, Jesús se reúne con sus discípulos en Galilea antes de ascender al cielo.",
 "Jesús les da la gran comisión: hacer discípulos de todas las naciones. Algunos todavía dudaban. La tarea era inmensa y Él se iba.",
 "El miedo a quedarse solos ante una misión enorme.",
 "La misión termina con una promesa: «yo estoy con vosotros todos los días». No algunos días, no solo los buenos días: todos. Es la última frase del Evangelio de Mateo, que había empezado anunciando a «Emanuel, Dios con nosotros».",
 "Si hoy estás enfrentando soledad o sientes que tienes que cumplir tu propósito por tu cuenta, recuerda la última promesa de Jesús. Hoy también es uno de «todos los días». Háblale durante tus tareas como a alguien que está a tu lado.",
 "Jesús, gracias porque estás conmigo todos los días. Hoy renuncio a la soledad y al miedo de no poder. Voy a donde me envías sabiendo que tú vas conmigo hasta el fin. Amén.",
 ["soledad", "obediencia"], ["gran comisión", "presencia de Jesús", "misión", "discipulado"], ["soledad", "miedo", "duda"])

# ---------------------------------------------------------------- IGLESIA
add("hch-9-4", "iglesia", "Hechos 9:4-6", "Hechos", "Jesús resucitado",
 "Saulo, Saulo, ¿por qué me persigues?… Yo soy Jesús a quien tú persigues: dura cosa te es dar coces contra el aguijón… Levántate y entra en la ciudad, y se te dirá lo que te conviene hacer.",
 "Saulo de Tarso (el futuro apóstol Pablo)", ["Pablo", "Saulo", "Ananías"],
 "Hacia el año 34 d. C. La iglesia crecía en Jerusalén y más allá. Saulo, un fariseo celoso, perseguía a los cristianos.",
 "Saulo iba camino a Damasco con cartas para arrestar a los seguidores de Jesús. De repente, una luz del cielo lo rodeó y cayó a tierra.",
 "El fanatismo, la violencia y el orgullo de quien cree tener toda la razón.",
 "Jesús se identifica tanto con su iglesia que perseguirla es perseguirlo a Él. Pero no destruye a Saulo: lo llama. El mayor perseguidor se convertiría en el mayor misionero. Nadie está fuera del alcance de la gracia.",
 "Si hoy estás enfrentando la convicción de que has estado yendo en la dirección equivocada, no te resistas: dar coces contra el aguijón solo duele más. Levántate, da el siguiente paso y deja que Dios te muestre lo que te conviene hacer.",
 "Jesús, reconozco que he luchado contra ti. Hoy renuncio al orgullo y dejo de resistirme. Cambia mi camino como cambiaste el de Pablo. Dime qué quieres que haga. Amén.",
 ["culpa", "obediencia"], ["conversión", "gracia", "llamado", "transformación"], ["orgullo", "fanatismo", "culpa", "resistencia a Dios"])

add("hch-10-15", "iglesia", "Hechos 10:15", "Hechos", "La voz del Señor",
 "Lo que Dios limpió, no lo llames tú común.",
 "El apóstol Pedro, en Jope", ["Pedro", "Cornelio"],
 "Hacia el año 40 d. C. La iglesia estaba formada casi solo por judíos, que no se relacionaban con gentiles (no judíos).",
 "Pedro oraba en una azotea y tuvo una visión: un lienzo con animales impuros y una voz que le decía que comiera. Él se negó. Mientras tanto, un centurión romano llamado Cornelio lo buscaba.",
 "El prejuicio, la exclusión y el menosprecio hacia otros.",
 "Dios le enseña a Pedro que no debe llamar impuro a nadie a quien Él haya aceptado. Poco después Pedro entró a casa de Cornelio y el Espíritu Santo descendió sobre los gentiles. El amor de Dios no tiene fronteras.",
 "Si hoy estás enfrentando prejuicios —hacia otros o de otros hacia ti—, escucha esta palabra. Nadie es «demasiado impuro» para Dios. Acércate hoy a alguien distinto a ti con respeto y amor.",
 "Señor, perdona mis prejuicios. Hoy renuncio a menospreciar a quien tú has amado. Ensancha mi corazón para ver a cada persona como tú la ves. Amén.",
 ["amor"], ["inclusión", "prejuicio", "gentiles", "gracia"], ["prejuicio", "rechazo", "exclusión"])

add("hch-13-2", "iglesia", "Hechos 13:2", "Hechos", "El Espíritu Santo",
 "Apartadme a Bernabé y a Saulo para la obra para la cual los he llamado.",
 "La iglesia de Antioquía", ["Bernabé", "Pablo", "Saulo"],
 "Hacia el año 47 d. C. Antioquía de Siria se había convertido en un centro de la iglesia con judíos y gentiles.",
 "Los profetas y maestros de la iglesia ministraban al Señor y ayunaban cuando el Espíritu Santo habló. Así empezó el primer viaje misionero.",
 "La incertidumbre sobre el propósito y la vocación.",
 "El Espíritu Santo habla en un contexto de adoración y ayuno. Tiene un propósito específico para personas concretas. El llamado de Dios se descubre en comunidad, en oración y en disponibilidad.",
 "Si hoy estás enfrentando dudas sobre tu propósito o vocación, busca la dirección de Dios como la iglesia de Antioquía: en oración, en adoración y en comunidad. Pregúntale a personas de fe que te conocen qué ven en ti.",
 "Espíritu Santo, quiero escuchar tu voz. Hoy renuncio a la confusión sobre mi propósito. Apártame para la obra para la que me has llamado y dame un corazón disponible. Amén.",
 ["obediencia"], ["llamado", "misión", "Espíritu Santo", "vocación"], ["falta de propósito", "confusión", "indecisión"])

add("hch-18-9", "iglesia", "Hechos 18:9-10", "Hechos", "El Señor",
 "No temas, sino habla, y no calles: porque yo estoy contigo, y ninguno te podrá hacer mal; porque yo tengo mucho pueblo en esta ciudad.",
 "El apóstol Pablo, en Corinto", ["Pablo", "Silas", "Timoteo"],
 "Hacia el año 51 d. C., en Corinto, una ciudad grande, rica y conocida por su inmoralidad.",
 "Pablo había sido rechazado, golpeado y expulsado de varias ciudades. En Corinto la oposición volvía a crecer y él pensaba callar o marcharse.",
 "El miedo a hablar de la fe y el desgaste de la oposición.",
 "Incluso el gran apóstol Pablo tuvo miedo. Dios lo anima en visión nocturna con tres razones: estoy contigo, nadie te dañará, y tengo mucha gente aquí. Pablo se quedó año y medio y nació una iglesia.",
 "Si hoy estás enfrentando miedo a hablar de tu fe, a decir la verdad o a mantenerte firme en un lugar difícil, recuerda que Dios está contigo y tiene propósito en ese lugar. Habla con amor y no calles lo que Dios puso en tu corazón.",
 "Señor, tengo miedo de hablar. Hoy renuncio al temor y al silencio. Tú estás conmigo y tienes gente en este lugar. Dame valor y palabras llenas de amor. Amén.",
 ["miedo", "obediencia"], ["valentía", "testimonio", "presencia de Dios", "misión"], ["miedo", "miedo a hablar", "oposición"])

add("2co-12-9", "iglesia", "2 Corintios 12:9", "2 Corintios", "El Señor",
 "Bástate mi gracia; porque mi potencia en la flaqueza se perfecciona.",
 "El apóstol Pablo", ["Pablo"],
 "Hacia el año 56 d. C. Pablo escribe a los corintios, que dudaban de su autoridad y preferían líderes elocuentes e impresionantes.",
 "Pablo sufría un «aguijón en la carne», un padecimiento que no explica. Rogó tres veces a Dios que se lo quitara.",
 "La debilidad, el sufrimiento que no se va y la sensación de ser insuficiente.",
 "Dios no le quitó el aguijón a Pablo, pero le dio algo mejor: su gracia suficiente. El poder de Dios se muestra con más claridad en nuestra debilidad. Pablo terminó diciendo: «cuando soy flaco, entonces soy poderoso».",
 "Si hoy estás enfrentando una debilidad, enfermedad o limitación que no desaparece aunque has orado, escucha esta respuesta. Tu debilidad no es un obstáculo para Dios. Pídele gracia para hoy, solo para hoy, y deja que su poder se muestre en ti.",
 "Señor, te he pedido que quites mi aguijón. Hoy renuncio a la frustración y a la vergüenza por mi debilidad. Tu gracia me basta. Perfecciona tu poder en mi flaqueza. Amén.",
 ["fe", "tristeza"], ["gracia", "debilidad", "sufrimiento", "poder de Dios"], ["debilidad", "enfermedad", "frustración", "insuficiencia"])

# ---------------------------------------------------------------- APOCALIPSIS
add("apo-1-17", "apocalipsis", "Apocalipsis 1:17-18", "Apocalipsis", "Jesús glorificado",
 "No temas: yo soy el primero y el último; y el que vivo, y he sido muerto; y he aquí que vivo por siglos de siglos, Amén. Y tengo las llaves del infierno y de la muerte.",
 "El apóstol Juan, desterrado en Patmos", ["Juan"],
 "Hacia el año 95 d. C. Los cristianos sufrían persecución bajo el emperador Domiciano. Juan, ya anciano, estaba desterrado en la isla de Patmos.",
 "Juan tuvo una visión de Cristo glorificado, con ojos como llama de fuego y rostro como el sol. Cayó como muerto a sus pies.",
 "El miedo a la muerte, a la persecución y al futuro.",
 "Jesús pone su mano sobre Juan y le dice «no temas». Él venció a la muerte y tiene sus llaves. Para un pueblo perseguido, esta palabra significaba que ni el emperador ni la muerte tenían la última palabra.",
 "Si hoy estás enfrentando miedo a la muerte, a la enfermedad o a lo que viene, imagina la mano de Jesús sobre tu hombro. Él vive para siempre y tiene las llaves. Lo que te asusta no tiene la última palabra.",
 "Jesús, tú eres el primero y el último. Hoy renuncio al miedo a la muerte y al futuro. Tú vives y tienes las llaves. Pon tu mano sobre mí y dame paz. Amén.",
 ["miedo", "esperanza"], ["resurrección", "muerte", "victoria", "persecución"], ["miedo a la muerte", "persecución", "miedo al futuro"])

add("apo-3-20", "apocalipsis", "Apocalipsis 3:20", "Apocalipsis", "Jesús glorificado",
 "He aquí, yo estoy a la puerta y llamo: si alguno oyere mi voz y abriere la puerta, entraré a él, y cenaré con él, y él conmigo.",
 "La iglesia de Laodicea", ["Juan", "iglesia de Laodicea"],
 "Laodicea era una ciudad rica, famosa por sus bancos, su industria textil y un colirio medicinal. Es la última de las siete cartas a las iglesias.",
 "La iglesia se creía rica y sin necesidad de nada, pero Jesús la llama tibia, pobre, ciega y desnuda.",
 "La autosuficiencia, la tibieza espiritual y la soledad de una vida sin comunión con Dios.",
 "Después de una corrección fuerte, Jesús se presenta como alguien que toca a la puerta con paciencia. No la derriba: espera ser invitado. Cenar juntos era signo de amistad íntima.",
 "Si hoy estás enfrentando un vacío interior aunque «lo tengas todo», o una fe tibia, escucha el llamado a tu puerta. Abre tu vida a Jesús en lo cotidiano: invítalo a tu mesa, a tus conversaciones, a tus decisiones.",
 "Jesús, te escucho llamar a mi puerta. Hoy renuncio a la autosuficiencia y a la tibieza. Te abro. Entra, cena conmigo y quédate en mi vida. Amén.",
 ["soledad", "amor"], ["comunión", "intimidad", "tibieza", "invitación"], ["tibieza", "autosuficiencia", "vacío", "soledad"])

add("apo-21-5", "apocalipsis", "Apocalipsis 21:5-6", "Apocalipsis", "Dios, sentado en el trono",
 "He aquí, yo hago nuevas todas las cosas… Yo soy el Alfa y la Omega, el principio y el fin. Al que tuviere sed, yo le daré de la fuente del agua de vida gratuitamente.",
 "El apóstol Juan, para toda la iglesia", ["Juan"],
 "Visión final del libro. Juan ve un cielo nuevo y una tierra nueva, y la nueva Jerusalén descendiendo del cielo.",
 "Una gran voz anuncia que Dios morará con los hombres y que limpiará toda lágrima de sus ojos: ya no habrá muerte, ni llanto, ni clamor, ni dolor. Entonces habla el que está sentado en el trono.",
 "La tristeza, el dolor y la muerte que hoy afectan al mundo.",
 "El Dios que dijo «sea la luz» en Génesis cierra la historia diciendo «hago nuevas todas las cosas». No solo cosas nuevas, sino todas las cosas nuevas. El que empezó la historia es también quien la termina, y la termina bien.",
 "Si hoy estás enfrentando tristeza, dolor o lágrimas que parecen interminables, recuerda el final de la historia. Dios limpiará toda lágrima. Mientras tanto, acude a Él con tu sed: te da agua de vida gratuitamente.",
 "Dios eterno, principio y fin, hoy renuncio a la tristeza que me dice que el dolor es para siempre. Tú haces nuevas todas las cosas. Limpia mis lágrimas y dame de beber del agua de vida. Amén.",
 ["esperanza", "tristeza"], ["cielo nuevo", "nueva creación", "eternidad", "consuelo"], ["tristeza", "dolor", "duelo", "desesperanza"])

add("apo-22-20", "apocalipsis", "Apocalipsis 22:20", "Apocalipsis", "Jesús glorificado",
 "Ciertamente, vengo en breve.",
 "Toda la iglesia, a través de Juan", ["Juan"],
 "Son las últimas palabras de Jesús en la Biblia. Cierran la revelación dada a Juan en Patmos.",
 "La iglesia vivía perseguida y esperando. Juan responde: «Amén, sea así. Ven, Señor Jesús».",
 "La espera larga, el cansancio de esperar y la tentación de perder la esperanza.",
 "Las últimas palabras que Dios pronuncia en la Biblia son una promesa de regreso. Toda la historia avanza hacia un reencuentro. El final no es un vacío, sino una persona que viene.",
 "Si hoy estás enfrentando el cansancio de esperar —justicia, sanidad, respuestas—, deja que esta promesa renueve tu esperanza. Vive hoy como alguien que espera a quien ama: con fidelidad, con alegría y con los ojos en el horizonte.",
 "Señor Jesús, creo en tu promesa. Hoy renuncio a la desesperanza de la espera. Ven, Señor Jesús. Mientras tanto, ayúdame a vivir fiel y con los ojos puestos en ti. Amén.",
 ["esperanza"], ["segunda venida", "espera", "promesa", "fin de los tiempos"], ["desesperanza", "cansancio", "espera"])
